version: "3.9"
configs:
  prometheus_config:
    file: .Server/prometheus.yml

services:
  server:
    image: vagacr.azurecr.io/vag-server
    build: ./Server
    ports:
      - "5001:5001"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
    volumes:
      - ./Server/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./Server/Grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./Server/Grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - prometheus

  client:
      image: vagacr.azurecr.io/vag-front
      build:
        context: .
        dockerfile: Client/Dockerfile
      ports:
        - "8080:80"
      depends_on:
      - server
