version: "3.9"

services:
  server:
    image: vagacr.azurecr.io/vag-server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "5001:5001"
    deploy:
      resources:
        limits:
          cpus: '0.5'

  prometheus:
    image: vagacr.azurecr.io/vag-prometheus
    build: ./Server/Prometheus
    ports:
      - "9090:9090"
    depends_on:
      - server
    deploy:
      resources:
        limits:
          cpus: '0.5'
  
  grafana:
    image: vagacr.azurecr.io/vag-grafana
    build: ./Server/Grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: '0.5'

  client:
    image: vagacr.azurecr.io/vag-front
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
    - server
    deploy:
      resources:
        limits:
          cpus: '0.5'
