{
 "title": "Measurements",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Engine RPM",
   "type": "gauge",
   "description": "Engine RPM ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "PID_ENGINE_RPM" }
   ]
  },
  {
   "title": "Vehicle speed",
   "type": "gauge",
   "description": "Vehicle speed km/h",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "PID_VEHICLE_SPEED" }
   ]
  },
  {
   "title": "Engine RPM time series",
   "type": "timeseries",
   "description": "Shows RPM in time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "PID_ENGINE_RPM" }
   ]
  },
  {
   "title": "Vehicle speed time series",
   "type": "timeseries",
   "description": "Shows the vehicle speed in time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    { "expr": "PID_VEHICLE_SPEED" }
   ]
  },
  {
   "title": "Throttle position",
   "type": "timeseries",
   "description": "Describes throttle position percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "PID_THROTTLE" }
   ]
  },
  {
   "title": "Engine load",
   "type": "timeseries",
   "description": "Shows engine load percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "PID_ABSOLUTE_ENGINE_LOAD" }
   ]
  },
  {
   "title": "Fuel pressure",
   "type": "timeseries",
   "description": "Fuel pressure in kPa",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    { "expr": "PID_FUEL_PRESSURE" }
   ]
  },
  {
   "title": "Intake air temperature",
   "type": "timeseries",
   "description": "Intake air temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "PID_INTAKE_TEMP" }
   ]
  },
  {
   "title": "Coolant temperature",
   "type": "timeseries",
   "description": "Coolant temperature in Celsius",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "PID_COOLANT_TEMP" }
   ]
  },
  {
   "title": "Intake manifold absolute pressure",
   "type": "timeseries",
   "description": "Intake manifold absolute pressure in kPa",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    { "expr": "PID_INTAKE_MAP" }
   ]
  },
  {
   "title": "Mass air flow sensor air flow rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "targets": [
    { "expr": "PID_MAF_FLOW" }
   ]
  }
 ]
}