// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteCarDiagz.Server.Data;

namespace RemoteCarDiagz.Server.Migrations
{
    [DbContext(typeof(RemoteCarDiagzContext))]
    [Migration("20211019165206_ActiveMeasurements")]
    partial class ActiveMeasurements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RemoteCarDiagz.Shared.Domain.Measurement", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("Value");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Value = 4,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 5,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 10,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 11,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 12,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 13,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 15,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 16,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 17,
                            IsActive = false,
                            IsAvailable = true
                        },
                        new
                        {
                            Value = 67,
                            IsActive = false,
                            IsAvailable = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
