// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteCarDiagz.Server.Data;

namespace RemoteCarDiagz.Server.Migrations
{
    [DbContext(typeof(RemoteCarDiagzContext))]
    [Migration("20211018074315_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RemoteCarDiagz.Server.Data.Measurement", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Value");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Value = 4,
                            IsActive = false
                        },
                        new
                        {
                            Value = 5,
                            IsActive = false
                        },
                        new
                        {
                            Value = 6,
                            IsActive = false
                        },
                        new
                        {
                            Value = 7,
                            IsActive = false
                        },
                        new
                        {
                            Value = 8,
                            IsActive = false
                        },
                        new
                        {
                            Value = 9,
                            IsActive = false
                        },
                        new
                        {
                            Value = 10,
                            IsActive = false
                        },
                        new
                        {
                            Value = 11,
                            IsActive = false
                        },
                        new
                        {
                            Value = 12,
                            IsActive = false
                        },
                        new
                        {
                            Value = 13,
                            IsActive = false
                        },
                        new
                        {
                            Value = 14,
                            IsActive = false
                        },
                        new
                        {
                            Value = 15,
                            IsActive = false
                        },
                        new
                        {
                            Value = 16,
                            IsActive = false
                        },
                        new
                        {
                            Value = 17,
                            IsActive = false
                        },
                        new
                        {
                            Value = 30,
                            IsActive = false
                        },
                        new
                        {
                            Value = 31,
                            IsActive = false
                        },
                        new
                        {
                            Value = 33,
                            IsActive = false
                        },
                        new
                        {
                            Value = 44,
                            IsActive = false
                        },
                        new
                        {
                            Value = 45,
                            IsActive = false
                        },
                        new
                        {
                            Value = 46,
                            IsActive = false
                        },
                        new
                        {
                            Value = 47,
                            IsActive = false
                        },
                        new
                        {
                            Value = 48,
                            IsActive = false
                        },
                        new
                        {
                            Value = 49,
                            IsActive = false
                        },
                        new
                        {
                            Value = 50,
                            IsActive = false
                        },
                        new
                        {
                            Value = 51,
                            IsActive = false
                        },
                        new
                        {
                            Value = 60,
                            IsActive = false
                        },
                        new
                        {
                            Value = 61,
                            IsActive = false
                        },
                        new
                        {
                            Value = 62,
                            IsActive = false
                        },
                        new
                        {
                            Value = 63,
                            IsActive = false
                        },
                        new
                        {
                            Value = 66,
                            IsActive = false
                        },
                        new
                        {
                            Value = 67,
                            IsActive = false
                        },
                        new
                        {
                            Value = 68,
                            IsActive = false
                        },
                        new
                        {
                            Value = 69,
                            IsActive = false
                        },
                        new
                        {
                            Value = 70,
                            IsActive = false
                        },
                        new
                        {
                            Value = 71,
                            IsActive = false
                        },
                        new
                        {
                            Value = 72,
                            IsActive = false
                        },
                        new
                        {
                            Value = 73,
                            IsActive = false
                        },
                        new
                        {
                            Value = 74,
                            IsActive = false
                        },
                        new
                        {
                            Value = 75,
                            IsActive = false
                        },
                        new
                        {
                            Value = 76,
                            IsActive = false
                        },
                        new
                        {
                            Value = 77,
                            IsActive = false
                        },
                        new
                        {
                            Value = 78,
                            IsActive = false
                        },
                        new
                        {
                            Value = 82,
                            IsActive = false
                        },
                        new
                        {
                            Value = 89,
                            IsActive = false
                        },
                        new
                        {
                            Value = 91,
                            IsActive = false
                        },
                        new
                        {
                            Value = 92,
                            IsActive = false
                        },
                        new
                        {
                            Value = 93,
                            IsActive = false
                        },
                        new
                        {
                            Value = 94,
                            IsActive = false
                        },
                        new
                        {
                            Value = 97,
                            IsActive = false
                        },
                        new
                        {
                            Value = 98,
                            IsActive = false
                        },
                        new
                        {
                            Value = 99,
                            IsActive = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
